### ISSUE TITLE
No exports defined

### ISSUE THREAD

**Issue by siiky** [diamond-lizard/srfi-67#4]
Hi,

I installed SRFI 67 today and noticed that `compare-list` is undefined (try `csi -R srfi-67 -p compare-list`). I looked at the code and, indeed, nothing is exported from the `srfi-67` module:

https://github.com/diamond-lizard/srfi-67/blob/6764e44aa55707b141123ec3bb796fb3bef25318/srfi-67.scm#L1

`klovett` in IRC found the list of exports from the SRFI and shared them here: https://paste.call-cc.org/paste?id=5be239bb2900a540f5bfda05115798d58e6e1c5a

I'm wondering if you'd be able to update the egg and publish a new version, or, in case you're no longer active in CHICKEN, you'd be willing to give up maintainership to someone else.

**Comment by diamond-lizard** [comment]
Hello, thank you for your bug report, but I am no longer maintaining any of the SRFIs that I contributed to chicken.  I believe their maintenance was taken over by others from the larger chicken community.  You may want to check the chicken wiki or reach out on the chicken mailing list to find out where the appropriate place to submit this issue is.
